// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aegis/AlertScreen.tsx": () => import("../components/mockups/aegis/AlertScreen.tsx"),
  "./components/mockups/aegis/DashboardScreen.tsx": () => import("../components/mockups/aegis/DashboardScreen.tsx"),
  "./components/mockups/aegis/HomeScreen.tsx": () => import("../components/mockups/aegis/HomeScreen.tsx"),
  "./components/mockups/aegis/SafeWordScreen.tsx": () => import("../components/mockups/aegis/SafeWordScreen.tsx"),
  "./components/mockups/aegis/SandboxScreen.tsx": () => import("../components/mockups/aegis/SandboxScreen.tsx"),
  "./components/mockups/aegis/SettingsScreen.tsx": () => import("../components/mockups/aegis/SettingsScreen.tsx"),
  "./components/mockups/aegis/VoiceAlertScreen.tsx": () => import("../components/mockups/aegis/VoiceAlertScreen.tsx"),
  "./components/mockups/aegis/shared/AegisNavMenu.tsx": () => import("../components/mockups/aegis/shared/AegisNavMenu.tsx")
};
